test::
	rm -rf
	python -m venv venv
	. venv/bin/activate && pip install -U pip
	. venv/bin/activate && pip install streamlit
	. venv/bin/activate && pip install -U -i https://test.pypi.org/simple/ st-iframe-postmessage
	. venv/bin/activate && streamlit run test_app.py
